export const GLOBAL_QUESTIONS = [
    { id: 1, question: "What is the capital of Afghanistan?", options: ["Kabul", "Algiers", "Luanda", "Buenos Aires"], answer: "Kabul" },
    { id: 2, question: "Which country has a population of approximately 38 million people?", options: ["Norway", "Finland", "Greece", "Poland"], answer: "Poland" },
    { id: 3, question: "What is the area of Canada in square kilometers?", options: ["9,984,670", "1,285,216", "2,780,400", "3,287,263"], answer: "9,984,670" },
    { id: 4, question: "Which country shares a border with Belgium?", options: ["Spain", "Germany", "Italy", "Portugal"], answer: "Germany" },
    { id: 5, question: "What is the capital of Argentina?", options: ["Buenos Aires", "Jakarta", "Kingston", "Nairobi"], answer: "Buenos Aires" },
    { id: 6, question: "Which country has a population of approximately 126 million people?", options: ["South Korea", "Vietnam", "Japan", "Australia"], answer: "Japan" },
    { id: 7, question: "What is the area of Brazil in square kilometers?", options: ["5,964,917", "8,515,767", "7,692,024", "6,652,000"], answer: "8,515,767" },
    { id: 8, question: "Which country shares a border with Chile?", options: ["Brazil", "Uruguay", "Peru", "Argentina"], answer: "Argentina" },
    { id: 9, question: "What is the capital of Egypt?", options: ["Athens", "Rabat", "Khartoum", "Cairo"], answer: "Cairo" },
    { id: 10, question: "Which country has a population of approximately 1.4 billion people?", options: ["China", "Indonesia", "Russia", "Mexico"], answer: "China" },
    { id: 11, question: "What is the area of India in square kilometers?", options: ["1,960,582", "2,149,690", "4,320,722", "3,287,263"], answer: "3,287,263" },
    { id: 12, question: "Which country shares a border with France?", options: ["Ireland", "Spain", "Iceland", "Sweden"], answer: "Spain" },
    { id: 13, question: "What is the capital of Italy?", options: ["Rome", "Paris", "Lisbon", "Vienna"], answer: "Rome" },
    { id: 14, question: "Which country has a population of approximately 83 million people?", options: ["Canada", "Malaysia", "Germany", "Saudi Arabia"], answer: "Germany" },
    { id: 15, question: "What is the area of Russia in square kilometers?", options: ["9,526,468", "17,098,242", "12,141,000", "8,515,767"], answer: "17,098,242" },
    { id: 16, question: "Which country shares a border with South Africa?", options: ["Kenya", "Zambia", "Namibia", "Tanzania"], answer: "Namibia" },
    { id: 17, question: "What is the capital of Spain?", options: ["Berlin", "Budapest", "Prague", "Madrid"], answer: "Madrid" },
    { id: 18, question: "Which country has a population of approximately 67 million people?", options: ["France", "Thailand", "Colombia", "Australia"], answer: "France" },
    { id: 19, question: "What is the area of Australia in square kilometers?", options: ["5,684,403", "7,692,024", "8,123,602", "3,287,263"], answer: "7,692,024" },
    { id: 20, question: "Which country shares a border with Germany?", options: ["Poland", "Turkey", "Ireland", "Norway"], answer: "Poland" },
    { id: 21, question: "What is the capital of Kenya?", options: ["Accra", "Dakar", "Lusaka", "Nairobi"], answer: "Nairobi" },
    { id: 22, question: "Which country has a population of approximately 211 million people?", options: ["Brazil", "Pakistan", "Nigeria", "Bangladesh"], answer: "Brazil" },
    { id: 23, question: "What is the area of Argentina in square kilometers?", options: ["4,324,000", "3,287,263", "1,564,100", "2,780,400"], answer: "2,780,400" },
    { id: 24, question: "Which country shares a border with India?", options: ["Cambodia", "Philippines", "Nepal", "Thailand"], answer: "Nepal" },
    { id: 25, question: "What is the capital of South Korea?", options: ["Seoul", "Tokyo", "Beijing", "Hanoi"], answer: "Seoul" },
    { id: 26, question: "Which country has a population of approximately 59 million people?", options: ["Italy", "South Africa", "Myanmar", "Ukraine"], answer: "Italy" },
    { id: 27, question: "What is the area of Saudi Arabia in square kilometers?", options: ["3,144,170", "1,284,000", "1,730,648", "2,149,690"], answer: "2,149,690" },
    { id: 28, question: "Which country shares a border with Thailand?", options: ["Singapore", "Malaysia", "Myanmar", "Indonesia"], answer: "Myanmar" },
    { id: 29, question: "What is the capital of Canada?", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"], answer: "Ottawa" },
    { id: 30, question: "Which country has a population of approximately 19 million people?", options: ["Zambia", "Romania", "Netherlands", "Sri Lanka"], answer: "Romania" },
    { id: 31, question: "What is the area of Mexico in square kilometers?", options: ["1,964,375", "1,287,000", "2,945,000", "3,457,540"], answer: "1,964,375" },
{ id: 32, question: "Which country shares a border with Ukraine?", options: ["Poland", "Greece", "Portugal", "Norway"], answer: "Poland" },
{ id: 33, question: "What is the capital of Vietnam?", options: ["Hanoi", "Phnom Penh", "Vientiane", "Bangkok"], answer: "Hanoi" },
{ id: 34, question: "Which country has a population of approximately 10 million people?", options: ["Portugal", "Jordan", "Sweden", "Tunisia"], answer: "Portugal" },
{ id: 35, question: "What is the area of Sudan in square kilometers?", options: ["1,886,068", "2,035,152", "1,234,567", "3,287,263"], answer: "1,886,068" },
{ id: 36, question: "Which country shares a border with Brazil?", options: ["Argentina", "Ecuador", "Uruguay", "Colombia"], answer: "Argentina" },
{ id: 37, question: "What is the capital of Greece?", options: ["Athens", "Sofia", "Bucharest", "Tirana"], answer: "Athens" },
{ id: 38, question: "Which country has a population of approximately 25 million people?", options: ["North Korea", "Taiwan", "Angola", "Malaysia"], answer: "North Korea" },
{ id: 39, question: "What is the area of Kazakhstan in square kilometers?", options: ["2,724,900", "1,904,569", "3,400,680", "2,075,340"], answer: "2,724,900" },
{ id: 40, question: "Which country shares a border with Iran?", options: ["Iraq", "Jordan", "Yemen", "Oman"], answer: "Iraq" },
{ id: 41, question: "What is the capital of Turkey?", options: ["Ankara", "Istanbul", "Izmir", "Antalya"], answer: "Ankara" },
{ id: 42, question: "Which country has a population of approximately 144 million people?", options: ["Russia", "Egypt", "Mexico", "Japan"], answer: "Russia" },
{ id: 43, question: "What is the area of Mongolia in square kilometers?", options: ["1,564,116", "1,240,192", "2,038,121", "1,986,000"], answer: "1,564,116" },
{ id: 44, question: "Which country shares a border with Saudi Arabia?", options: ["Jordan", "Lebanon", "Israel", "Turkey"], answer: "Jordan" },
{ id: 45, question: "What is the capital of Malaysia?", options: ["Kuala Lumpur", "Jakarta", "Manila", "Bangkok"], answer: "Kuala Lumpur" },
{ id: 46, question: "Which country has a population of approximately 9 million people?", options: ["United Arab Emirates", "Portugal", "Sweden", "Hungary"], answer: "United Arab Emirates" },
{ id: 47, question: "What is the area of France in square kilometers?", options: ["551,695", "431,282", "640,679", "723,790"], answer: "551,695" },
{ id: 48, question: "Which country shares a border with Germany?", options: ["Switzerland", "Spain", "Ukraine", "Turkey"], answer: "Switzerland" },
{ id: 49, question: "What is the capital of Peru?", options: ["Lima", "Quito", "La Paz", "Santiago"], answer: "Lima" },
{ id: 50, question: "Which country has a population of approximately 50 million people?", options: ["South Korea", "Canada", "Colombia", "Kenya"], answer: "South Korea" },
{ id: 51, question: "What is the area of Italy in square kilometers?", options: ["301,340", "421,852", "211,537", "390,541"], answer: "301,340" },
{ id: 52, question: "Which country shares a border with India?", options: ["Bangladesh", "Thailand", "Indonesia", "Iran"], answer: "Bangladesh" },
{ id: 53, question: "What is the capital of Norway?", options: ["Oslo", "Stockholm", "Copenhagen", "Helsinki"], answer: "Oslo" },
{ id: 54, question: "Which country has a population of approximately 37 million people?", options: ["Canada", "Venezuela", "Angola", "Greece"], answer: "Canada" },
{ id: 55, question: "What is the area of Egypt in square kilometers?", options: ["1,010,408", "1,320,000", "950,612", "1,134,583"], answer: "1,010,408" },
{ id: 56, question: "Which country shares a border with Argentina?", options: ["Chile", "Paraguay", "Bolivia", "Uruguay"], answer: "Chile" },
{ id: 57, question: "What is the capital of Nigeria?", options: ["Abuja", "Lagos", "Accra", "Nairobi"], answer: "Abuja" },
{ id: 58, question: "Which country has a population of approximately 83 million people?", options: ["Germany", "Thailand", "Turkey", "Vietnam"], answer: "Germany" },
{ id: 59, question: "What is the area of Spain in square kilometers?", options: ["505,992", "432,000", "567,234", "690,787"], answer: "505,992" },
{ id: 60, question: "Which country shares a border with Italy?", options: ["Switzerland", "France", "Belgium", "Slovenia"], answer: "Switzerland" },
{ id: 61, question: "What is the capital of New Zealand?", options: ["Wellington", "Auckland", "Christchurch", "Hamilton"], answer: "Wellington" },
{ id: 62, question: "Which country has a population of approximately 83 million people?", options: ["Egypt", "Australia", "Canada", "Netherlands"], answer: "Egypt" },
{ id: 63, question: "What is the area of Algeria in square kilometers?", options: ["2,381,741", "1,345,230", "2,845,112", "1,678,000"], answer: "2,381,741" },
{ id: 64, question: "Which country shares a border with Poland?", options: ["Belarus", "Denmark", "Spain", "Finland"], answer: "Belarus" },
{ id: 65, question: "What is the capital of Finland?", options: ["Helsinki", "Oslo", "Stockholm", "Copenhagen"], answer: "Helsinki" },
{ id: 66, question: "Which country has a population of approximately 67 million people?", options: ["United Kingdom", "France", "Italy", "South Africa"], answer: "United Kingdom" },
{ id: 67, question: "What is the area of Nigeria in square kilometers?", options: ["923,768", "1,002,000", "810,892", "964,000"], answer: "923,768" },
{ id: 68, question: "Which country shares a border with Venezuela?", options: ["Colombia", "Argentina", "Chile", "Uruguay"], answer: "Colombia" },
{ id: 69, question: "What is the capital of Thailand?", options: ["Bangkok", "Hanoi", "Phnom Penh", "Vientiane"], answer: "Bangkok" },
{ id: 70, question: "Which country has a population of approximately 82 million people?", options: ["Iran", "Iraq", "Morocco", "Algeria"], answer: "Iran" },
{ id: 71, question: "What is the area of South Africa in square kilometers?", options: ["1,219,090", "1,002,000", "1,582,000", "820,000"], answer: "1,219,090" },
{ id: 72, question: "Which country shares a border with Canada?", options: ["United States", "Mexico", "Russia", "Greenland"], answer: "United States" },
{ id: 73, question: "What is the capital of Portugal?", options: ["Lisbon", "Porto", "Madrid", "Barcelona"], answer: "Lisbon" },
{ id: 74, question: "Which country has a population of approximately 10 million people?", options: ["Sweden", "Norway", "Denmark", "Finland"], answer: "Sweden" },
{ id: 75, question: "What is the area of France in square kilometers?", options: ["643,801", "501,000", "789,000", "1,002,000"], answer: "643,801" },
{ id: 76, question: "Which country shares a border with China?", options: ["Mongolia", "Japan", "Philippines", "Taiwan"], answer: "Mongolia" },
{ id: 77, question: "What is the capital of Colombia?", options: ["Bogotá", "Caracas", "Lima", "Quito"], answer: "Bogotá" },
{ id: 78, question: "Which country has a population of approximately 60 million people?", options: ["Italy", "Spain", "Poland", "Canada"], answer: "Italy" },
{ id: 79, question: "What is the area of Ukraine in square kilometers?", options: ["603,500", "720,000", "812,000", "500,000"], answer: "603,500" },
{ id: 80, question: "Which country shares a border with Greece?", options: ["Albania", "Turkey", "Italy", "Cyprus"], answer: "Albania" },
{ id: 81, question: "What is the capital of Switzerland?", options: ["Bern", "Zurich", "Geneva", "Basel"], answer: "Bern" },
{ id: 82, question: "Which country has a population of approximately 20 million people?", options: ["Romania", "Netherlands", "Chile", "Sri Lanka"], answer: "Romania" },
{ id: 83, question: "What is the area of Chile in square kilometers?", options: ["756,102", "689,400", "823,000", "914,500"], answer: "756,102" },
{ id: 84, question: "Which country shares a border with Austria?", options: ["Germany", "Spain", "Netherlands", "Denmark"], answer: "Germany" },
{ id: 85, question: "What is the capital of Australia?", options: ["Canberra", "Sydney", "Melbourne", "Brisbane"], answer: "Canberra" },
{ id: 86, question: "Which country has a population of approximately 4 million people?", options: ["New Zealand", "Luxembourg", "Iceland", "Malta"], answer: "New Zealand" },
{ id: 87, question: "What is the area of Denmark in square kilometers?", options: ["43,094", "32,000", "52,000", "64,500"], answer: "43,094" },
{ id: 88, question: "Which country shares a border with Norway?", options: ["Sweden", "Finland", "Denmark", "Iceland"], answer: "Sweden" },
{ id: 89, question: "What is the capital of Sweden?", options: ["Stockholm", "Oslo", "Helsinki", "Copenhagen"], answer: "Stockholm" },
{ id: 90, question: "Which country has a population of approximately 9 million people?", options: ["Austria", "Belgium", "Hungary", "Switzerland"], answer: "Austria" },
{ id: 91, question: "What is the area of Poland in square kilometers?", options: ["312,696", "421,000", "287,000", "369,500"], answer: "312,696" },
{ id: 92, question: "Which country shares a border with Japan?", options: ["Russia", "China", "South Korea", "Taiwan"], answer: "Russia" },
{ id: 93, question: "What is the capital of Austria?", options: ["Vienna", "Zurich", "Berlin", "Warsaw"], answer: "Vienna" },
{ id: 94, question: "Which country has a population of approximately 11 million people?", options: ["Greece", "Portugal", "Sweden", "Finland"], answer: "Greece" },
{ id: 95, question: "What is the area of Finland in square kilometers?", options: ["338,455", "287,000", "412,000", "367,500"], answer: "338,455" },
{ id: 96, question: "Which country shares a border with Malaysia?", options: ["Thailand", "Indonesia", "Philippines", "Australia"], answer: "Thailand" },
{ id: 97, question: "What is the capital of Canada?", options: ["Delhi", "Montreal","Ottawa", "Vancouver"], answer: "Ottawa" },
{ id: 98, question: "Which country has a population of approximately 5 million people?", options: ["Norway", "Denmark", "Finland", "Estonia"], answer: "Norway" },
{ id: 99, question: "What is the area of Belgium in square kilometers?", options: ["30,528", "25,000", "32,000", "29,500"], answer: "30,528" },
{ id: 100, question: "Which country shares a border with Argentina?", options: ["Brazil", "Chile", "Colombia", "Paraguay"], answer: "Brazil" },
]